#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define VF 15
#define WHITE_PIXEL 0xFFFFFFFF
#define BLACK_PIXEL 0x00000000
#define MEMORY_SIZE 4096
#define SCREEN_WIDTH 64
#define SCREEN_HEIGHT 32
#define KEYPAD_SIZE 16
#define INVALID_KEY 0xFF
#define NUM_OF_REGISTERS 16
#define STACK_SIZE 16
#define START_ADDRESS 0x200
#define FONT_START 0x50
#define FONT_HEIGHT 5

#endif
